app:
  name: "web_app"
  mode: "dev"
  port: 8081
  version: "v0.0.1"
  start_time: "2023-10-11"
  machine_id: 1

auth:
  jwt_expire: 8760

log:
  level: "debug"
  filename: "web_app.log"
  max_size: 200
  max_age: 30
  max_backups: 7

mysql:
  host: 127.0.0.1
  port: 3306
  user: "root"
  password: "18861335365WAGMM"
  dbname: "web_app"

redis:
  host: "127.0.0.1"
  port: 6379
  password: ""
  db: 0
  pool_size: 100

